services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OpenDemat\ExampleBundle\:
    resource: '../../src/*'
    exclude: '../../src/{DependencyInjection,Tests,tests,ExampleBundle.php}'

  OpenDemat\ExampleBundle\Hub\ExampleGlobalAppDefinition:
    tags: ['open_demat.hub.app_definition']
