<?php

declare(strict_types=1);

namespace OpenDemat\ExampleBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527140254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the example internal purchase request process table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA IF NOT EXISTS example');
        $this->addSql('CREATE TABLE example.demande_achat_interne (demandeur VARCHAR(255) NOT NULL, service_demandeur VARCHAR(255) NOT NULL, intitule_besoin VARCHAR(255) NOT NULL, justification TEXT NOT NULL, montant_estime INT NOT NULL, type_achat VARCHAR(50) NOT NULL, fournisseur_souhaite VARCHAR(255) DEFAULT NULL, centre_cout VARCHAR(80) NOT NULL, date_besoin DATE DEFAULT NULL, urgence BOOLEAN NOT NULL, attestations JSON NOT NULL, commentaire_gestionnaire TEXT DEFAULT NULL, date_fin_process DATE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut_traitement VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE example.demande_achat_interne');
        $this->addSql('DROP SCHEMA example');
    }
}
